
# set condition for when to run the action files 
on: 
  push: 
    branches: ["master"]
# build docker image , push dockerhub
env: 
  DOCKER_IMAGE_NAME: k8s-reactjs-dev09
jobs: 
  ci-job: 
    runs-on: ubuntu-latest 
    environment: DOCKER_ENV
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Using Commit SHA 
        run: |
          echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
      - name: Show the SHA values 
        run: |
          echo "TAG = ${{env.TAG }}"
      - name: Login to Dockerhub 
        run: |
          echo "${{ secrets.PASSWORD }}" | docker login -u ${{secrets.USERNAME}} --password-stdin
      - name: Build and Tag 
        run: |
          docker build -t ${{ secrets.USERNAME }}/${{ env.DOCKER_IMAGE_NAME }} .
      - name: Push to Dockerhub 
        run: |
          docker push ${{ secrets.USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
      - name: Logout from Dockerhub 
        if: always()
        run: |
          docker logout 
# update helm repo with new image